---
name-template: v{{version}}
tag-template: v{{version}}
categories:
  - title: 🚨 Breaking Changes
    labels:
      - breaking change
    bump: major
  - title: ✨ New Features
    labels:
      - feature
    bump: minor
  - title: 🐛 Bug Fixes
    labels:
      - fix
    bump: patch
  - title: 🛠 Maintenance
    labels:
      - chore
      - refactor
    bump: patch
change-template: "- {{change.title}} by @{{change.author}} (#{{change.number}})"
no-changes-template: "- No significant changes"
template: |
  ## What's Changed
  $CHANGES

  ## Contributors
  $CONTRIBUTORS
