---
name-template: v{{version}}
tag-template: v{{version}}
categories:
  - title: 🚨 Breaking Changes
    labels:
      - breaking change
    bump: major
  - title: ✨ New Features
    labels:
      - feature
    bump: minor
  - title: 🐛 Bug Fixes
    labels:
      - fix
    bump: patch
  - title: 🛠 Maintenance
    labels:
      - chore
      - refactor
     bump: patch
  - title: 📖 Documentation Updates
    labels:
      - documentation
      - docs
  - title: 🌟 Improvements
    labels:
      - improvement
      - optimization
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
no-changes-template: "- No significant changes"
template: |
  ## What's Changed
  $CHANGES

  ## Contributors
  $CONTRIBUTORS
version-resolver:
  major:
    labels:
      - major
      - breaking-change
  minor:
    labels:
      - minor
      - feature
  patch:
    labels:
      - patch
      - fix
      - bug
      - chore
      - maintenance
  default: patch
