template: |
  ## What's Changed
  $CHANGES
name-template: Release v${{ env.NEXT_MAJOR }}.${{ env.NEXT_MINOR }}.${{ env.NEXT_PATCH }}
tag-template: v${{ env.NEXT_MAJOR }}.${{ env.NEXT_MINOR }}.${{ env.NEXT_PATCH }}
categories:
  - title: 🚀 Features
    labels:
      - feature
      - enhancement
      - new-feature
  - title: 🐛 Bug Fixes
    labels:
      - fix
      - bugfix
      - bug
      - defect
  - title: 🔧 Maintenance
    labels:
      - chore
      - refactor
      - maintenance
  - title: 📖 Documentation Updates
    labels:
      - documentation
      - docs
  - title: 🌟 Improvements
    labels:
      - improvement
      - optimization
change-template: "- {{change.title}} by @{{change.author}} (#{{change.number}})"
version-resolver:
  major:
    labels:
      - major
      - breaking-change
  minor:
    labels:
      - minor
      - feature
  patch:
    labels:
      - patch
      - fix
      - bug
      - chore
      - maintenance
  default: patch
